name: FinOps Cost Audit Template

on:
  workflow_dispatch:  # Manual trigger only (no automatic runs)

jobs:
  cost-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run EC2 idle instance scanner
        run: python3 main.py

      - name: Commit report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add reports/
          git commit -m "Add EC2 idle report" || echo "No changes"
          git push

